BUILD_DIR=build
include $(N64_INST)/include/n64.mk

PROJECT_NAME = "raymarcher"

N64_CXXFLAGS += -std=gnu++20 -Os -fno-exceptions -fsingle-precision-constant

# $(BUILD_DIR)/src/raymarch.o: N64_CXXFLAGS += -O3 -ffast-math

src = $(wildcard src/*.cpp) $(wildcard src/math/*.cpp)
src += $(wildcard src/rdp/*.cpp) $(wildcard src/rsp/*.cpp)
src += $(wildcard src/camera/*.cpp)

assets_png = $(wildcard assets/*.tex.png)

assets_conv = $(patsubst assets/%,filesystem/%,$(assets_png:%.tex.png=%.tex))

all: $(PROJECT_NAME).z64

#filesystem/%.sprite: assets/%.png
#	@mkdir -p $(dir $@)
#	@echo "    [SPRITE] $@"
#	$(N64_MKSPRITE) $(MKSPRITE_FLAGS) -o $(dir $@) "$<"

filesystem/%.tex: assets/%.tex.png
	@mkdir -p $(dir $@)
	@echo "    [IMG] $@ $<"
	./tools/imgconv/imgconv "$<" $@
	$(N64_BINDIR)/mkasset -c 1 -o $(dir $@) $@

build/%.dfs:
	@mkdir -p $(dir $@)
	@echo "    [DFS*] $@ $(<D)"
	$(N64_MKDFS) $@ filesystem >/dev/null

tools/imgconv/imgconv:
	@echo "    [BUILD] imgconv"
	@make -C tools/imgconv

# RSP metadata
$(SOURCE_DIR)/src/rsp/rsp_raymarch_layout.h: $(BUILD_DIR)/src/rsp/rsp_raymarch.o
	@echo "    [RSP_METADATA] $<"
	echo "// NOTE: this file is autogenerated by the Makefile of t3d!" > $(SOURCE_DIR)/src/rsp/rsp_raymarch_layout.h
	$(N64_GCCPREFIX_TRIPLET)objdump -S -t $(BUILD_DIR)/src/rsp/rsp_raymarch.elf \
		| grep ".data	" | grep -v emux \
		| awk '{print "#define", "RSP_RAY_" $$5, "0x" $$1;}' \
		>> $(SOURCE_DIR)/src/rsp/rsp_raymarch_layout.h
	$(N64_GCCPREFIX_TRIPLET)objdump -S -t $(BUILD_DIR)/src/rsp/rsp_raymarch.elf \
		| grep ".bss	" | grep -v emux \
		| awk '{print "#define", "RSP_RAY_BSS_" $$5, "0x" $$1;}' \
		>> $(SOURCE_DIR)/src/rsp/rsp_raymarch_layout.h
	$(N64_GCCPREFIX_TRIPLET)objdump -S -t $(BUILD_DIR)/src/rsp/rsp_raymarch.elf \
		| grep ".text	" | grep -v emux \
		| awk '{print "#define", "RSP_RAY_CODE_" $$5, "0x" $$1;}' \
		>> $(SOURCE_DIR)/src/rsp/rsp_raymarch_layout.h

$(BUILD_DIR)/src/raymarch.o: $(SOURCE_DIR)/src/rsp/rsp_raymarch_layout.h

$(BUILD_DIR)/$(PROJECT_NAME).dfs: $(assets_conv)
$(BUILD_DIR)/$(PROJECT_NAME).elf: $(src:%.cpp=$(BUILD_DIR)/%.o) $(BUILD_DIR)/src/rsp/rsp_raymarch.o

$(PROJECT_NAME).z64: N64_ROM_TITLE="Raymarcher 64"
$(PROJECT_NAME).z64: $(BUILD_DIR)/$(PROJECT_NAME).dfs

fonts:
	node tools/createFont.mjs assets/font.png src/font.h
	node tools/createFontDelta.mjs assets/font64.png src/font64.h

sc64:
	make -j8
	curl 192.168.0.6:9065/off
	sleep 1
	sc64deployer --remote 192.168.0.6:9064 upload --tv ntsc *.z64
	curl 192.168.0.6:9065/on

sc64r:
	make -j8
	sc64deployer --remote 192.168.0.6:9064 upload --tv ntsc *.z64
	sleep 1
	curl 192.168.0.6:9065/reset

clean:
	rm -rf $(BUILD_DIR) *.z64
	rm -rf filesystem

-include $(wildcard $(BUILD_DIR)/*.d)

.PHONY: all clean
